# .github/workflows/generate-video.yml

name: Generate Video

on:
  workflow_dispatch:
    inputs:
      theme:
        description: 'Tema do vídeo'
        required: true
        default: 'Curiosidades sobre o MAR'
        type: string
  repository_dispatch:
    types: [generate-video]

jobs:
  generate-video:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install dependencies
      # MUDANÇA AQUI: 'npm install' vai ler o package.json e instalar tudo
      run: npm install

    - name: Install system tools
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg

    - name: Generate video frames and compile
      env:
        THEME: ${{ github.event.inputs.theme || github.event.client_payload.theme || 'Curiosidades sobre o MAR' }}
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
      run: |
        xvfb-run -a node puppeteer-script.js

    - name: Upload result
      uses: actions/upload-artifact@v4
      with:
        name: generated-video
        path: output/final-video.mp4
