name: Generate Video

on:
  workflow_dispatch: # Permite executar manualmente

jobs:
  generate-video:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install dependencies
      run: |
        npm install puppeteer

    - name: Install system tools
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg

    - name: Generate video
      run: |
        xvfb-run -a node puppeteer-script.js

    - name: Combine video and audio
      run: |
        if [ -f output/video.webm ] && [ -f output/audio.wav ]; then
          ffmpeg -i output/video.webm -i output/audio.wav -c:v libx264 -c:a aac -shortest output/final-video.mp4
        fi

    - name: Upload result
      uses: actions/upload-artifact@v4
      with:
        name: generated-video
        path: output/
